spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: drop
  h2:
    console:
        path: /h2
        enabled: true

